### ISSUE TITLE
no ads display.

### ISSUE THREAD

**Issue by gchenfly** [DanielnetoDotCom/YouPHPTube#1174]
I create ads campaign.
But why there is no ads display?
And what is the ads content?

**Comment by DanielnetoDotCom** [comment]
did you add videos on your campaign.

**Comment by gchenfly** [comment]
yes. i add videos which i uploaded on campaign.
But there are no ads display on the videos.
I am confused that what is the ads?  Is the video on campaign, or another ad video will display on the video on campaign.
Or some parameter wrong?

**Comment by gchenfly** [comment]
I want to know is the video that added to the campaign is ads or not?
Or is there any ads will display on this video?
who is the advertiser and what is the advertise content?

**Comment by DanielnetoDotCom** [comment]
when you add videos on the campaign, this video will be the ad. and will appear in all other videos.

**Comment by gchenfly** [comment]
I try several times, unfortunately, there is no success.
And i check the js console, find this:
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin().
Is this the problem? how to solve it?
Many thanks.

**Comment by DanielnetoDotCom** [comment]
`VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin(). `this is just a warning, will not be fixed now.

can you try to do the same on the demo site?
see if works there?

what is your site URL?

FYI, on demo site, you will need to disable the GoogleAds_IMA  plugin before enabling the AD_Server  plugin

**Comment by gchenfly** [comment]
I tried the demo site.
It is NOT work. I check the console, get the same warning!
My site:
http://35.185.139.30/YouPHPTube/

**Comment by gchenfly** [comment]
My browser: Google chrome

**Comment by DanielnetoDotCom** [comment]
I checked the demo site, the problem was the start time. You need to paid attention to that

My server time is 10:04 am
The campaign was set to start at 20 o clock.

I just fixed the start time and all works fine

![image](https://user-images.githubusercontent.com/18009293/47605112-8d34a100-d9d8-11e8-8987-45a530130681.png)

![image](https://user-images.githubusercontent.com/18009293/47605125-9cb3ea00-d9d8-11e8-8eaa-66a10bbce16f.png)

**Comment by gchenfly** [comment]
Yes. The demo site is working.
But My site is still not work!
Here is the error:
![2018-10-27 10 44 21](https://user-images.githubusercontent.com/34537998/47605518-057f7e80-da3a-11e8-9360-4f91f467ca55.png)

**Comment by gchenfly** [comment]
Hi.
Can you give any solution for this problem.
It is important for me to use YouPHPTube as my startup project.
I deploy it in google cloud. Is it the reason?
For google has default google ads. Are these two conflict?
I can not find google ads plugin in my own site. but there is one in demo site.

**Comment by gchenfly** [comment]
Is demo site deploy in google cloud?
Is this problem associate with google chrome?

**Comment by DanielnetoDotCom** [comment]
Hi, the demo is not on google cloud
I am not sure what is happening on your side

**Comment by gchenfly** [comment]
OK. I will try it myself later.
I want to change the theme of first page as follow:
delete the latest post video at the top, and replace it with a category of recommendation, like youtube does.
Can i design new theme and upload?
Any tutorial about this topic?
Thanks again for your great work.

**Comment by DanielnetoDotCom** [comment]
Sure, new themes will be great.

Try to modify the gallery plugin, it is a good start

I don't have any tutorial yet, but should not be hard to understand

**Comment by DanielnetoDotCom** [comment]
@karen20ced4 lets keep track it here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1218#issuecomment-438664658
