### ISSUE TITLE
Live Chat crashing

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1385]
[13-Jan-2019 17:31:06 America/New_York] Error in writeSql : (1452) Cannot add or update a child row: a foreign key constraint fails (`PuyoTube`.`videos_statistics`, CONSTRAINT `fk_videos_statistics_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE), SQL-CMD:INSERT INTO videos_statistics ( `id`,`when`,`ip`,`users_id`,`videos_id`,`created`,`modified`,`lastVideoTime` ) VALUES ( NULL ,  '2019-01-13 05:31:06' ,  NULL ,  '0' ,  '22' ,  now() ,  now() ,  '920' ) 

is the error i get when trying to start the chat server

**Comment by Puyodead1** [comment]
Fixed by dropping LiveChat table and re installing it

**Comment by lunar54** [comment]
Even after dropping LiveChat  table and reinstalling it still getting 
nohup: ignoring input and appending output to 'nohup.out'  
site not usable. I had root login set to yes in ssh config so I could check logs/files easier with winscp so i disabled it then I del the file nohup.out file then restarted server. I still get nohup: ignoring input and appending output to 'nohup.out   but its working again

**Comment by lunar54** [comment]
Is this a normal log entry in youphptube.log ?

#0 /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/MyDomain.net/html/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164

**Comment by lunar54** [comment]
just cleaned out log and restarted server now i got error in there

PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/MyDomain.net/html/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/MyDomain.net/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164

**Comment by DanielnetoDotCom** [comment]
If you chat is already running is OK to have it on the log file

this happens because the stript is trying to start the chat, but the chat is already active.
