### ISSUE TITLE
Configurations and Streamers tabs are missing on a fresh install of YouPHPTube-Encoder

### ISSUE THREAD

**Issue by danionescu2007** [DanielnetoDotCom/YouPHPTube#238]
I noticed here https://github.com/DanielnetoDotCom/YouPHPTube/issues/140 that there is more to Encoder than I could personally see.

I followed this tutorial to install everything: https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-Encoder

I was looking for a way to alter the quality of the encoded videos when I noticed the screenshot in the above linked issue (quality of the videos #140).

I also checked under /var/www/html/encoder/videos/configuration.php
$global['disableConfigurations'] = false;
... but there is no COnfiguration tab, neither a Streamers one:
<img width="1889" alt="screen shot 2017-11-26 at 01 20 54" src="https://user-images.githubusercontent.com/4688610/33235780-ecd9770e-d248-11e7-936f-03408229648e.png">

Please advise, thank you,
Dan

**Comment by DanielnetoDotCom** [comment]
For some reason your streamer user is not a admin on encoder.
Take a look on your database and change the column isAdmin to 1

see this https://github.com/DanielnetoDotCom/YouPHPTube/issues/207

**Comment by danionescu2007** [comment]
Thanks for the quick answer and strait to the core of the problem. I am puting here also my sql to help debug or maybe prevent for future installs. 'Cause I made a fresh install and the database and tables and records where created by the web-install of the Encoder module.

`mysql> use `youPHPTube-Encoder`
Database changed
mysql> show tables;
+------------------------------+
| Tables_in_youPHPTube-Encoder |
+------------------------------+
| configurations               |
| encoder_queue                |
| formats                      |
| streamers                    |
+------------------------------+
4 rows in set (0.00 sec)

mysql> describe streamers;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(11)      | NO   | PRI | NULL    | auto_increment |
| siteURL  | varchar(255) | NO   |     | NULL    |                |
| user     | varchar(45)  | NO   |     | NULL    |                |
| pass     | varchar(45)  | NO   |     | NULL    |                |
| priority | int(11)      | NO   |     | 3       |                |
| isAdmin  | tinyint(1)   | NO   |     | 0       |                |
| created  | datetime     | YES  |     | NULL    |                |
| modified | datetime     | YES  |     | NULL    |                |
+----------+--------------+------+-----+---------+----------------+
8 rows in set (0.01 sec)

mysql> select * from streamers;
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
| id | siteURL              | user  | pass                             | priority | isAdmin | created             | modified            |
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
|  1 | http://172.16.1.238  | admin | ftw5r@HOME                       |        1 |       1 | 2017-11-26 01:09:41 | 2017-11-26 01:09:41 |
|  2 | http://172.16.1.238/ | admin | 2fa4b7066bbc741326c64a8ccb6051d8 |        1 |       0 | 2017-11-26 01:10:14 | 2017-11-26 01:10:14 |
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
2 rows in set (0.00 sec)

mysql> update streamers set isAdmin=1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 2  Changed: 1  Warnings: 0

mysql> select * from streamers;
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
| id | siteURL              | user  | pass                             | priority | isAdmin | created             | modified            |
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
|  1 | http://172.16.1.238  | admin | ftw5r@HOME                       |        1 |       1 | 2017-11-26 01:09:41 | 2017-11-26 01:09:41 |
|  2 | http://172.16.1.238/ | admin | 2fa4b7066bbc741326c64a8ccb6051d8 |        1 |       1 | 2017-11-26 01:10:14 | 2017-11-26 01:10:14 |
+----+----------------------+-------+----------------------------------+----------+---------+---------------------+---------------------+
2 rows in set (0.00 sec)`

**Comment by DanielnetoDotCom** [comment]
We can see the problem is the slash at the end of siteURL.
I will try to release some fix for that soon

**Comment by danionescu2007** [comment]
Thank you for your kind support. I already fixed my issue. Now I have the admin api user empowered and the tabs are showing alright. Please feel free to close the current issue.

**Comment by republicus** [comment]
This issue is still present on v 7.2.
Updating the database as above did restore the additional tabs.

Additionally, it also appears the settings
`$global['disableBulkEncode'] = true;`
`$global['disableWebM'] = true;`
 in the configuration.php are ignored when set to true for admin users.

**Comment by DanielnetoDotCom** [comment]
Hi @republicus 

I do not get what do you mean.

**Comment by guymass** [comment]
I am havgin the same issue after a clean new install on a new server I can only see 2 Tabs under the Encoder page:
![Screen Shot 5781-02-13 at 19 50 17](https://user-images.githubusercontent.com/58882903/97786168-740bef80-1bb2-11eb-8ac4-7e7e1728c622.jpg)

**Comment by DanielnetoDotCom** [comment]
by default, the encoder admin is the first user (the one you use to install)

the site admin is not the encoder admin, they are different.

but you can make any user admin using the command line. (https://github.com/WWBN/AVideo-Encoder/blob/master/install/makeAdmin.php)

go to your encoder installation directory and type this:

`php makeAdmin.php`

then it will prompt you to the user name you want to make encoder admin. 

after that logoff and login again.
