### ISSUE TITLE
Send mail  SMTP connect() failed. 

### ISSUE THREAD

**Issue by Spartacus2018** [DanielnetoDotCom/YouPHPTube#551]
Hello when i try to send mail i have this error : 
`
`Le message n'a pas pu être envoyé SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting``

![image](https://user-images.githubusercontent.com/301074/38247826-d446f65e-3746-11e8-8b1f-04623247efe7.png)

i configure my smtp server on the config  : 

![image](https://user-images.githubusercontent.com/301074/38247796-b9d061ac-3746-11e8-82b6-bcaac72e0521.png)

do u know how fix it ?

**Comment by DanielnetoDotCom** [comment]
Check the **Enable SMTP Auth** button

**Comment by DanielnetoDotCom** [comment]
I found something similar on a server...

and here is the solution...
https://stackoverflow.com/questions/22927634/smtp-connect-failed-phpmailer-php

> what you really need to do is .. log into your google account and open up following address https://www.google.com/settings/security/lesssecureapps and check turn on . you have to do this for letting you to connect with the google SMTP because according to new authentication mechanism google bounce back all the requests from all those applications which does not follow any standard encryption technique.. after checking turn on.. you are good to go.. here is the code which worked fine for me..

**Comment by ChrisSlS** [comment]
I have the same problem but I do not use the SMTP google, it's my host's, how can I fix it please ?

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS what the log file say when you try to send an email?

**Comment by ChrisSlS** [comment]
No error on my logfile :/

But, I followed the instructions as shown here:

https://webolio.wordpress.com/2008/03/02/phpmailer-and-smtp-on-1and1-shared-hosting/#comment-89

Does not work again, and the log file returns me this:

`[21-Apr-2018 17:56:13 Europe/Berlin] PHP Notice:  Use of undefined constant “smtp” - assumed '“smtp”' in /var/www/html/YouPHPTube/objects/functions.php on line 352`

So I returned to basic trimming, waiting to find the solution.

**Comment by DanielnetoDotCom** [comment]
hi, did you change the /var/www/html/YouPHPTube/objects/functions.php file?

In my file is something different
https://github.com/DanielnetoDotCom/YouPHPTube/blob/021584b7b37988032d4fd2e896c3adfafd5eecaf/objects/functions.php#L352

Google SMTP works it no problem on other sites I have configured

**Comment by ChrisSlS** [comment]
No, I put the file back in the original state, "IsSendmail" is written.

I have the same message as the author of the issue :

![](https://user-images.githubusercontent.com/301074/38247826-d446f65e-3746-11e8-8b1f-04623247efe7.png)

my mailbox is provided with my domain, namely 1and1.

**Comment by ChrisSlS** [comment]
Ok, my problem was solved in a curious way ... I had already set port 587, except that there was a problem. What I did is go to my gmail box and add my mail pro. Once done, it worked the first time. So I delete the pro account from gmail and it works fine, but to be honest I do not understand why gmail managed to make it work, although it is delete now as I said.

@Spartacus2018  try this... with luck, may be.

**Comment by DanielnetoDotCom** [comment]
Thanks for your help ChrisSIS

**Comment by Spartacus2018** [comment]
Hello, 
for me still not working, now with the test mail bouton i have this error : 

![image](https://user-images.githubusercontent.com/301074/40103869-283500c0-58ef-11e8-83f7-84c9ded81fe4.png)


i m looking how configure sendMail on my linux server

**Comment by DanielnetoDotCom** [comment]
you need to chech the "Activar SMTP" and "Activar Authentication SMTP" 

Click in save and then test the email

**Comment by willtsuru** [comment]
Hi all,
The same problems happened with me. I solved it modifying the tls port to 587 using gmail server. But here I think we have 2 possible problems

1) Whats happen when we use the gmail smtp is that we are working in my point of view in a insecure way as we after send the test e-mail we receive ans e-mail from google communicating me that my account was locked due to an insecure aplication. Not only this but according with google e-mail my account had the security level steped down leaving it wake. 
If Im not wrong what phpmailer do here is sent an e-mail without authentication that is a clear security hole.

...So I delete the pro account from gmail and it works fine, but to be honest I do not understand why gmail managed to make it work, although it is delete now as I said.....

Here seems that the google stepdown the security level of the main email account thats why even deleting the added account its still working (maybe assuming that the origin ip of the email still the same)
Maybe the best solution is setup the sendmail function in php.ini but some people can think this is hard.

 2) I dont like use google smtp as the e-mails are scanned as every ones know.

I dont know if Im right or not but if possible can someone correct me?

William Tsuruta

**Comment by DanielnetoDotCom** [comment]
@willtsuru for my personal use I use https://www.mailgun.com/, I am very satisfied with it.

I can configure my domain there to receive and send email using custom emails.

I have setup postfix on my server to relay the emails to mailgun.
Also I have setup my gmail to send emails using my domain/mailgun

**Comment by willtsuru** [comment]
Hi thanks for the update. I have my own mail server that works with smtp auth. I want if possible use it to handle the mils of the system. So please if you have some information on how to explaining what to modify on phpmailer to make it works please let me know dear.

**Comment by DanielnetoDotCom** [comment]
I use phpmailer with my postfix/mailgun on the same server as apache

I dont remember how I did to configure it, but I have fount it on google

**Comment by willtsuru** [comment]
Ok thanks I will search for.
I have a question about play list but Im new here must I start a new topic or something like this to inquiry you my friend?

**Comment by DanielnetoDotCom** [comment]
Please make a new topic, lets try to make it organized

**Comment by willtsuru** [comment]
Ok i will do

**Comment by roquirawnez** [comment]
Hey, sorry for asking but i've nearly the same problem.
I try to connect to my own exchange server, but recieve
 the error "SMTP Connect() failed".

<img width="776" alt="phpmailer" src="https://user-images.githubusercontent.com/41065691/44329434-b3801280-a464-11e8-9a42-bef6c9f42d2b.PNG">

**Comment by everyonecodesnoonequits** [comment]
We have an internal smtp relay we use for sending internal messages.  It is open internally, no smtp auth nor SSL required.  The system does not appear to be working with just having the server and standard port 25 in there.  

Confirmed on the youphptube server on cli that it can send an smtp message to the smtp server but the php app is still failing with the same settings.

**Comment by DanielnetoDotCom** [comment]
what error does appear on your log file?

**Comment by everyonecodesnoonequits** [comment]
Nothing is appearing in log files.  But I’m getting a popup on the site that the system seems to be expecting a local MTA for sendmail to be present.  It is saying that it is unable to execute the sendmail command locally.

**Comment by DanielnetoDotCom** [comment]
I am not sure what error should appear. 

you can delete the log file, try to send an email and paste the full log here, so we can check if there is a clue.

**Comment by everyonecodesnoonequits** [comment]
Is it normal for this app to look for a local sendmail?  Or should it construct its own SMTP message and send it to the external MTA?

Chad

**Comment by DanielnetoDotCom** [comment]
I guess it is because you did not fill the TLS or SSL field on the SMTP configuration.

**Comment by everyonecodesnoonequits** [comment]
OK there is no TLS or SSL.  It’s just straight up port 25 with no user authentication for our internal mail relay.

**Comment by DanielnetoDotCom** [comment]
I am not sure then.

I use PHPMailer

you have to make sure that use SMTP is on and SMTPAuth is off. I guess with this it may work.

otherwise you will need to debug the code to see what can be done to make it work
