### ISSUE TITLE
 install issues on 18.04 "Help Please"

### ISSUE THREAD

**Issue by Datamatrix1967** [DanielnetoDotCom/YouPHPTube#796]
Still unable to install YouPHPTube on  unbuntu 18.04
error listed below 
Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Jun 25 20:53:57 UTC 2018

  System load:  0.0               Processes:             86
  Usage of /:   40.1% of 9.78GB   Users logged in:       1
  Memory usage: 4%                IP address for enp0s3: 192.168.*.*
  Swap usage:   0%

93 packages can be updated.
43 updates are security updates.

Last login: Mon Jun 25 20:41:41 2018 from 192.168.0.15
*****@*****:~$ sudo apt-get install apache2 php7.1 libapache2-mod-php7.1 php7.1-mysql php7.1-curl php7.1-gd php7.1-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
[sudo] password for *****:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php7.1
E: Couldn't find any package by glob 'php7.1'
E: Couldn't find any package by regex 'php7.1'
E: Unable to locate package libapache2-mod-php7.1
E: Couldn't find any package by glob 'libapache2-mod-php7.1'
E: Couldn't find any package by regex 'libapache2-mod-php7.1'
E: Unable to locate package php7.1-mysql
E: Couldn't find any package by glob 'php7.1-mysql'
E: Couldn't find any package by regex 'php7.1-mysql'
E: Unable to locate package php7.1-curl
E: Couldn't find any package by glob 'php7.1-curl'
E: Couldn't find any package by regex 'php7.1-curl'
E: Unable to locate package php7.1-gd
E: Couldn't find any package by glob 'php7.1-gd'
E: Couldn't find any package by regex 'php7.1-gd'
E: Unable to locate package php7.1-intl
E: Couldn't find any package by glob 'php7.1-intl'
E: Couldn't find any package by regex 'php7.1-intl'
E: Package 'ffmpeg' has no installation candidate
E: Unable to locate package libimage-exiftool-perl
*****@*****:~$

**Comment by Datamatrix1967** [comment]
Updated still error
sudo apt-get update.
sudo apt-get upgrade


Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Jun 25 21:17:35 UTC 2018

  System load:  0.71              Processes:             89
  Usage of /:   43.4% of 9.78GB   Users logged in:       1
  Memory usage: 4%                IP address for enp0s3: 192.168.*.*
  Swap usage:   0%


0 packages can be updated.
0 updates are security updates.


Last login: Mon Jun 25 21:16:28 2018
*****@*****:~$ sudo apt-get install apache2 php7.1 libapache2-mod-php7.1 php7.1-mysql php7.1-curl php7.1-gd php7.1-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
[sudo] password for nginx:
Sorry, try again.
[sudo] password for nginx:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.1-mapi' for regex 'php7.1'
E: Unable to locate package libapache2-mod-php7.1
E: Couldn't find any package by glob 'libapache2-mod-php7.1'
E: Couldn't find any package by regex 'libapache2-mod-php7.1'
E: Unable to locate package php7.1-mysql
E: Couldn't find any package by glob 'php7.1-mysql'
E: Couldn't find any package by regex 'php7.1-mysql'
E: Unable to locate package php7.1-curl
E: Couldn't find any package by glob 'php7.1-curl'
E: Couldn't find any package by regex 'php7.1-curl'
E: Unable to locate package php7.1-gd
E: Couldn't find any package by glob 'php7.1-gd'
E: Couldn't find any package by regex 'php7.1-gd'
E: Unable to locate package php7.1-intl
E: Couldn't find any package by glob 'php7.1-intl'
E: Couldn't find any package by regex 'php7.1-intl'
*****@*****:~$

**Comment by hersche** [comment]
thanks for that issue.

it's a bit weird, i find those packages with apt search, but when i try the command, i agree with you..

i have corrected it here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

remove the version-nr leads to php 7.2, but that should work as well.. i also quick-tested the commands and got no error anymore from apt.

hope, this works for you as well?

**Comment by Datamatrix1967** [comment]
thanks for the quick reply - has cleared alot but still getting

nginx@nginx:~$ sudo apt-get install apache2 php libapache2-mod-php
php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git
libimage-exiftool-perl && cd /var/www/html && sudo git clone
https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html &&
sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git
&& sudo apt-get install python && sudo curl -L
https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
&& sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
[sudo] password for nginx:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php-intl
E: Package 'ffmpeg' has no installation candidate
E: Unable to locate package libimage-exiftool-perl

**Comment by MarkOnDuty** [comment]
I did a couple of installs on 18.04 this morning. As long as I had done an 'apt-get update' and 'apt-get upgrade' I could get everything to install successfully. I did run into some problems further down the line though, and ended up installing on 16.04, which has mostly worked as far as I can tell.

**Comment by Datamatrix1967** [comment]
wll try fresh install and let you know thanks for the help been trying nto
get it to work for the last couple of days 👍

**Comment by DanielnetoDotCom** [comment]
BTW on Ubuntu 18 is NOT php7.1 
you should replace all php7.1 to **php7.2**

I have it installed on Ubuntu 18 and the php version is PHP 7.2.5

**Comment by hersche** [comment]
i retried the first command, worked through, now i am on the install-page.

@MarkOnDuty where does it fail for you?
i just reconized, that if the YouPHPTube-folder already exist, git clone failed, and with this, everything that should be executed after it.
would it help here, to list the commands line after line? then it's more clear which command fails

@DanielnetoDotCom if i do a apt search, i can choose between php7.1 and 7.2 - both get installed
this is weird, and i rechecked if i have a repo / ppa added, but does not look like that.

anyway, withouth any version-nr, it automaticly takes php 7.2.. and its already replaced :)

**Comment by Datamatrix1967** [comment]
it has installed with no error but hasn't asked for sql password for root

**Comment by hersche** [comment]
@Datamatrix1967 are you using ubuntu 18 now, or changed to 16?

with ubuntu 18.04 try this: https://linuxconfig.org/how-to-reset-root-mysql-password-on-ubuntu-18-04-bionic-beaver-linux

**Comment by hersche** [comment]
can may be reduced to this:
   sudo mysql_secure_installation

**Comment by hersche** [comment]
@Datamatrix1967 also when the above answer would work, i highly recommend you to update or download again.. some bugs mainly from this weekend gets fixed now, so you propably have those bugs until update.

**Comment by Datamatrix1967** [comment]
will retry and let you know outcome and thanks for all the help

**Comment by Datamatrix1967** [comment]
Hi All 
	Got it all working with your help.


>Installed Ubuntu server 18.04

>sudo apt-get update

>Installed https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

>sudo apt install phpmyadmin php-mbstring php-gettext

>sudo phpenmod mbstring

>sudo systemctl restart apache2

>sudo mysql

>SELECT user,authentication_string,plugin,host FROM mysql.user;

Output
+------------------+-------------------------------------------+-----------------------+-----------+
| user             | authentication_string                     | plugin                | host      |
+------------------+-------------------------------------------+-----------------------+-----------+
| root             |                                           | auth_socket           | localhost |
| mysql.session    | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| mysql.sys        | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| debian-sys-maint | *8486437DE5F65ADC4A4B001CA591363B64746D4C | mysql_native_password | localhost |
| phpmyadmin       | *5FD2B7524254B7F81B32873B1EA6D681503A5CA9 | mysql_native_password | localhost |
+------------------+-------------------------------------------+-----------------------+-----------+
5 rows in set (0.00 sec)


>ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';          "where password is you new password"

>FLUSH PRIVILEGES;

>SELECT user,authentication_string,plugin,host FROM mysql.user;

Output
+------------------+-------------------------------------------+-----------------------+-----------+
| user             | authentication_string                     | plugin                | host      |
+------------------+-------------------------------------------+-----------------------+-----------+
| root             | *DE06E242B88EFB1FE4B5083587C260BACB2A6158 | mysql_native_password | localhost |
| mysql.session    | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| mysql.sys        | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| debian-sys-maint | *8486437DE5F65ADC4A4B001CA591363B64746D4C | mysql_native_password | localhost |
| phpmyadmin       | *5FD2B7524254B7F81B32873B1EA6D681503A5CA9 | mysql_native_password | localhost |
+------------------+-------------------------------------------+-----------------------+-----------+
5 rows in set (0.00 sec)

Then run http://yourip_address/YouPHPTube/




All worked great 
Thanks for the help .

**Comment by hersche** [comment]
i have updated the article with the new information we collected here:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

tell me, if you have any corrections. i tried to hold the mysql-password-stuff simple, but linked to this issue and a extended article..

if it's fine, you can close the issue :)

**Comment by MarkOnDuty** [comment]
@hersche Sorry. Had to sleep.

My issues under Ubuntu 18.04 were caused by the unset MySQL root user password.

I'll try installing it under Ubuntu 18.04 again this morning. It is a simple matter for me to spin up a container and install. I can hammer on this until it is perfect.

**Comment by Datamatrix1967** [comment]
All working thanks again for the help

**Comment by soapstreams** [comment]
I had same issue and was able to resolve it. When and if you all ever have the time, can we please reconcile these two sets of instructions for installing the encoder:

https://github.com/YouPHPTube/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-YouPHPTube-Encoder

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

Thanks.

**Comment by akhilleusuggo** [comment]
@soapstreams Just replace any version from 7.1 to 7.2 and gonna work ( only if you're using ubuntu 18.04 )

**Comment by soapstreams** [comment]
You bet. I was able to figure it out and get it installed, but I was initially using the instructions from YouPHPTube-Encoder rather than YouPHPTube and they are quite different. Someone updated the encoder install instructions in the YouPHPTube wiki, but the install instructions in the YouPHPTube-Encoder wiki are a bit outdated.

**Comment by akhilleusuggo** [comment]
@soapstreams Yes it's very outdated . I think the actual version is 7.3 and I haven't tried it yet , and soon gonna be 7.4 


7.4 | 28 November 2019[102] | December 2022 | Typed Properties 2.0,[103] Preloading,[104] Null Coalescing Assignment Operator,[105] Improve openssl_random_pseudo_bytes,[106] Weak References,[107] FFI – Foreign Function Interface[108]Always available hash extension,[109] Password Hash Registry,[110] Split multibyte string,[111] Reflection for references,[112] Unbundle ext/wddx,[113] New custom object serialization mechanism[114]
-- | -- | -- | --


https://en.wikipedia.org/wiki/PHP
