### ISSUE TITLE
[Suggestion] SEO

### ISSUE THREAD

**Issue by itsflashpoint** [DanielnetoDotCom/YouPHPTube#857]
Can the next version have the ability to change the type of URL we will have? ex: watch?=###xx#xxx (#= number, x = letter), etc. and the description of the metainfo for search engines. Because when you Google your website this shows up: "The Best YouTube Clone Ever - YouPHPTube." I think having a custom description would be better.

**Comment by DanielnetoDotCom** [comment]
Hi, about the URL you can change it to the permanent link if you want
![image](https://user-images.githubusercontent.com/18009293/42690386-5f9f4724-867a-11e8-9949-abbfad807729.png)

About the description you can use the customize plugin ($4,99 USD) to change it
![image](https://user-images.githubusercontent.com/18009293/42690427-81536c10-867a-11e8-8f8a-0339716875e5.png)

**Comment by itsflashpoint** [comment]
Thank you! :D.

I enabled permalink but the links still stay the same? Do I need to do anything else?

**Comment by DanielnetoDotCom** [comment]
Sorry, something was missing on gallery plugin, it is fixed now

**Comment by itsflashpoint** [comment]
I am using the Netflix plugin, not the gallery plugin btw.

**Comment by itsflashpoint** [comment]
So the last fix didn't fix anything. I am still getting the old URL's

**Comment by DanielnetoDotCom** [comment]
Ok, I just sent some more updates, you will need to clear your browser cache, and you should be all set

**Comment by DanielnetoDotCom** [comment]
what do you mean randomize?

**Comment by itsflashpoint** [comment]
As in ?watch=randomnumbers/letters.

**Comment by DanielnetoDotCom** [comment]
Hi
I don't think this has anything about SEO 
But will looks like YouTube , then maybe implemented in the future

**Comment by itsflashpoint** [comment]
Nope its not, meta tags, site description are though.

**Comment by DanielnetoDotCom** [comment]
Hi, 

can you please explain more what **?watch=randomnumbers/letters** is about SEO?

**Comment by itsflashpoint** [comment]
As I've said before it doesn't.

I didn't want to make multiple threads when I could've made one,

**Comment by hersche** [comment]
what's the sense behind having a "random" video-url?
